<?php
/**
 * Created by PhpStorm.
 * User: bw_dev
 * Date: 25.03.2018
 * Time: 17:06
 */

namespace yozh\base\controllers;

class MigrateController extends \yii\console\controllers\MigrateController
{
	protected function addMigrationHistory( $version )
	{
		if( !preg_match( '/m000000_.*_dev$/', $version) ){
			parent::addMigrationHistory( $version ); // TODO: Change the autogenerated stub
		}
	}
	
}