<?php
/**
 * Created by PhpStorm.
 * User: bw_dev
 * Date: 30.09.2018
 * Time: 9:47
 */

namespace yozh\base\traits;

trait ReadOnlyAttributesTrait
{
	public function readOnlyAttributes( ?array $attributes = [] ): array
	{
		return array_unique( array_merge( $attributes, [
			'id',
		] ) );
		
	}
	
	public function isReadOnlyAttribute( string $name ): bool
	{
		return in_array( $name, $this->readOnlyAttributes() );
	}
	
	public function resetAttribute( $name )
	{
		if( $this->getOldAttribute( $name ) != $this->getAttribute( $name ) ) {
			$this->setAttribute( $name, $this->getOldAttribute( $name ) );
		}
	}
	
	// reset readOnlyAttributes
	public function beforeSave( $insert )
	{
		foreach( $this->readOnlyAttributes() as $readOnlyAttributeName ) {
			if( !$this->isNewRecord ){
				$this->resetAttribute( $readOnlyAttributeName );
			}
		}
		
		return parent::beforeSave( $insert ); // TODO: Change the autogenerated stub
	}
	
}