<?php

namespace yozh\base\models;

use Yii;
use yozh\base\interfaces\models\ActiveRecordInterface;
use yozh\base\models\BaseActiveQuery as ActiveQuery;
use yozh\base\traits\ActiveRecordTrait;
use yozh\base\traits\ObjectTrait;

class BaseModel extends \yii\db\ActiveRecord implements ActiveRecordInterface
{
	use ObjectTrait, ActiveRecordTrait;
	
	public function beforeSave( $insert )
	{
		foreach( $this->readOnlyAttributes() as $readOnlyAttributeName ) {
			if( !$this->isNewRecord ){
				$this->resetAttribute( $readOnlyAttributeName );
			}
		}
		
		return parent::beforeSave( $insert ); // TODO: Change the autogenerated stub
	}
	
	public function setAttributes( $values, $safeOnly = true )
	{
		parent::setAttributes( $values, $safeOnly ); // TODO: Change the autogenerated stub
		
		return $this;
	}
	
	
}