<?php
namespace yozh\template;

use Yii;

abstract class AssetsBundle extends \yii\web\AssetBundle
{

	public function registerAssetFiles( $view )
	{
		$filename = str_replace( '/', '-', Yii::$app->controller->route );
		
		if( is_file( "{$this->sourcePath}/js/$filename.js" ) ){
			$this->js[] = "js/$filename.js";
		}
		
		if( is_file( "{$this->sourcePath}/css/$filename.css" ) ){
			$this->css[] = "css/$filename.css";
		}
		
		parent::registerAssetFiles( $view ); // TODO: Change the autogenerated stub
	}
}