<?php
namespace yozh\base;

use Yii;

class AssetBundle extends \yii\web\AssetBundle
{
	public $sourcePath = __DIR__ .'/../assets/';
	
	public $css = [
		'css/yozh-base-bootstrap.css',
		//'css/yozh-base.css',
		//['css/yozh-base.print.css', 'media' => 'print'],
	];
	
	public $js = [
		'js/yozh-base.js'
	];
	
	public $publishOptions = [
		'forceCopy'       => true,
	];
	
	public $depends = [
		'yii\web\YiiAsset',
		'yii\bootstrap\BootstrapAsset',
	];

	public function registerAssetFiles( $view )
	{
		$filename = str_replace( '/', '-', Yii::$app->controller->route );
		
		if( is_file( "{$this->sourcePath}/js/$filename.js" ) ){
			$this->js[] = "js/$filename.js";
		}
		
		if( is_file( "{$this->sourcePath}/css/$filename.css" ) ){
			$this->css[] = "css/$filename.css";
		}
		
		parent::registerAssetFiles( $view ); // TODO: Change the autogenerated stub
	}
}